//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_XuatKhauGao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
            this.ChiTietLCs = new HashSet<ChiTietLC>();
            this.NgayQuyetDinhs = new HashSet<NgayQuyetDinh>();
            this.VanChuyens = new HashSet<VanChuyen>();
        }
    
        public int MaHoaDon { get; set; }
        public Nullable<System.DateTime> NgayOrder { get; set; }
        public Nullable<System.DateTime> NgayNhanHangdukien { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<int> Manhanvien { get; set; }
        public Nullable<int> IdHinhThucThanhToan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietLC> ChiTietLCs { get; set; }
        public virtual HinhThucThanhToan HinhThucThanhToan { get; set; }
        public virtual khachhang khachhang { get; set; }
        public virtual nhanvien nhanvien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NgayQuyetDinh> NgayQuyetDinhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VanChuyen> VanChuyens { get; set; }
    }
}
