//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_XuatKhauGao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NgayQuyetDinh
    {
        public int id { get; set; }
        public int idHoaDon { get; set; }
        public System.DateTime ngayLapLc { get; set; }
        public Nullable<System.DateTime> ngayHieuLuc { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
    }
}
