//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_XuatKhauGao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nhanvien()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int idnhanvien { get; set; }
        public string tennhanvien { get; set; }
        public string diachi { get; set; }
        public string gioitinh { get; set; }
        public Nullable<int> idphongban { get; set; }
        public Nullable<int> idLogin { get; set; }
    
        public virtual Dangnhap Dangnhap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual PhongBan PhongBan { get; set; }
    }
}
